name: house_decoration_web
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  http: ^1.2.1
  get_storage: ^2.1.1
  get: ^4.6.6
  url_launcher: ^6.3.0
  multi_image_layout: ^0.1.2
  flutter_staggered_grid_view: ^0.7.0
  photo_view: ^0.15.0
  flutter_speed_dial: ^7.0.0
  firebase_core: ^3.3.0

  cloud_firestore: ^5.2.1 



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/Almaza/bedroom1/
    - assets/images/Almaza/bedroom2/
    - assets/images/Almaza/guest_toilet/
    - assets/images/Almaza/master_bedroomtoilet/master_bedroom/
    - assets/images/Almaza/master_bedroomtoilet/toilet/
    - assets/images/Almaza/master_toilet/
    - assets/images/Almaza/reception/
    - assets/images/art_city/BEDROOM/
    - assets/images/art_city/LIVING_ROOM/
    - assets/images/art_city/MASTER_BEDROOM/
    - assets/images/art_city/RECEPTION/
    - assets/images/astoria/bedroom1/
    - assets/images/astoria/bedroom2/
    - assets/images/astoria/kitchen/
    - assets/images/astoria/master/
    - assets/images/astoria/reception/
    - assets/images/mountain_view_ivilla/bedroom1/
    - assets/images/mountain_view_ivilla/bedroom2/
    - assets/images/mountain_view_ivilla/guest_toilet/
    - assets/images/mountain_view_ivilla/LANDSCAPE/
    - assets/images/mountain_view_ivilla/master_bedroom/
    - assets/images/mountain_view_ivilla/reception/
    - assets/images/mountain_view_ivilla/staircase_living_room/
    - assets/images/mountain_view_ivilla/rooms_toilet/
    - assets/images/mountain_view_standalone/bedroom1/
    - assets/images/mountain_view_standalone/bedroom2/
    - assets/images/mountain_view_standalone/level1/
    - assets/images/mountain_view_standalone/master/
    - assets/images/mountain_view_standalone/roof/
    - assets/images/Porto/guest_toilet/
    - assets/images/Porto/living_room/
    - assets/images/Porto/master_bedroom/
    - assets/images/Porto/reception/
    - assets/images/project/dressing_room/
    - assets/images/project/kids_room/
    - assets/images/project/master_toilet/
    - assets/images/project/reception/
    - assets/images/rehab_city/bedroom1/
    - assets/images/rehab_city/bedroom2/
    - assets/images/rehab_city/master/
    - assets/images/rehab_city/reception/
    - assets/images/rehab_city/toilets/
    - assets/images/rehab_city/kitchen/
    - assets/images/West_Somid/boys_bedroom/
    - assets/images/West_Somid/girls_bedroom/
    - assets/images/West_Somid/guest_toilet/
    - assets/images/West_Somid/landscape/
    - assets/images/West_Somid/master_bedroom_toilet/master_room/ 
    - assets/images/West_Somid/master_bedroom_toilet/toilet/
    - assets/images/West_Somid/master_toilet/
    - assets/images/West_Somid/reception/
    - assets/icons/
  
    







    


    
   

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Regular.ttf
        - asset: assets/fonts/IBMPlexSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/IBMPlexSans-Italic.ttf
          style: italic
       
      

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages


flutter_assets:
    assets_path: assets/icons/
    output_path: lib/core/constants/assets.dart
   